FROM python:3.14-slim-trixie

WORKDIR /app

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY ./pyproject.toml ./uv.lock /app/

COPY ./common /app/common
COPY ./database_repository /app/database_repository
COPY ./worker /app/worker

RUN uv pip install --system --no-cache \
    --extra-index-url https://download.pytorch.org/whl/cpu \
    -e ./common \
    -e ./database_repository \
    -e ./worker

CMD ["python", "-m", "ml_service_worker"]
