services:
  backend:
    command: ["run"]
    volumes:
      - ../backend:/app
      - backend-data:/var/lib/app/data
    ports:
      - "${USERS_PORT:-8000}:8000"
      - "${WALLET_PORT:-8001}:8001"
      - "${MODEL_PORT:-8002}:8002"

  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  rabbitmq:
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"

  worker:
    volumes:
      - ../backend:/app
