services:
  backend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users.rule=Host(`${DOMAIN}`) && PathPrefix(`/users`)"
      - "traefik.http.routers.users.entrypoints=websecure"
      - "traefik.http.routers.users.tls.certresolver=letsencrypt"
      - "traefik.http.routers.users.service=users-svc"
      - "traefik.http.services.users-svc.loadbalancer.server.port=8000"
      - "traefik.http.routers.wallet.rule=Host(`${DOMAIN}`) && PathPrefix(`/wallet`)"
      - "traefik.http.routers.wallet.entrypoints=websecure"
      - "traefik.http.routers.wallet.tls.certresolver=letsencrypt"
      - "traefik.http.routers.wallet.service=wallet-svc"
      - "traefik.http.services.wallet-svc.loadbalancer.server.port=8001"
      - "traefik.http.routers.model.rule=Host(`${DOMAIN}`) && PathPrefix(`/model`)"
      - "traefik.http.routers.model.entrypoints=websecure"
      - "traefik.http.routers.model.tls.certresolver=letsencrypt"
      - "traefik.http.routers.model.service=model-svc"
      - "traefik.http.services.model-svc.loadbalancer.server.port=8002"

  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend.service=frontend-svc"
      - "traefik.http.services.frontend-svc.loadbalancer.server.port=3000"

  traefik:
    image: traefik:v3.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates-data:/letsencrypt
    networks:
      - ml_network
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=ml_network"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK__LETS_ENCRYPT_EMAIL:-test@example.com}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    restart: on-failure

volumes:
  traefik-certificates-data:
